Major update: bug fixes, new options, portability...

diff --git a/flactrack b/flactrack
--- a/flactrack
+++ b/flactrack
@@ -16,6 +16,7 @@
 # This script is designed to split single-file flac albums into tagged tracks.
 
 main(){
+	echo START
 	# Gather the metadata that's the same for all of the tracks
 	ALBUM=$( cat "$CUE" |
 		sed '/TRACK/q' |
@@ -25,20 +26,20 @@ main(){
 	GENRE=$( cat "$CUE" |
 		sed '/TRACK/q' |
 		grep "REM\sGENRE" |
-		sed 's/REM\sGENRE\s\(.*\).$/\1/' )
+		sed 's/\s*REM\s\s*GENRE\s\s*\(.*\).$/\1/' )
 	DATE=$( cat "$CUE" |
 		sed '/TRACK/q' |
-		grep "REM\sDATE\|YEAR" |
-		sed 's/REM\sDATE\s\|YEAR\s\(.*\).$/\1/' )
+		grep "REM\s\s*DATE\|YEAR" |
+		sed 's/\s*REM\s\s*DATE\|YEAR\s\s*\(.*\).$/\1/' )
 	TRACKTOTAL=$( grep TRACK.*AUDIO "$CUE" |
 		awk '{print $2}' |
 		tail -n1 |
 		sed 's/.*\([1-9]{2}\).*/\1/' )
 	# Try to find a cover image if one was not specified. Look for jpg first, then png.
 	oldIFS=$IFS && IFS=$(echo -en "\n\b")
-	if ! [ -a $COVER ]; then
+	if [ ! -f "$COVER" ] && [ "$COVER" != 0 ]; then
 		for IMAGE in $( find . -maxdepth 2 \( -iname \*.jpg -o -iname \*.jpeg \) ); do
-		    image=$( echo ${IMAGE,,} | sed 's/.*\/\(.*\)\.jpe\?g/\1/' )
+		    image=$( echo $IMAGE | sed -e 's/\(.*\)/\L\1/' -e 's/.*\/\(.*\)\.jpe\?g/\1/' )
 		    if [ "$image" == "cover" ] || [ "$image" == ".cover" ]; then
 				COVER=$IMAGE; break
 			elif [ "$image" == "folder" ] || [ "$image" == ".folder" ]; then
@@ -48,9 +49,9 @@ main(){
 		    fi
 		done
 	fi
-	if ! [ -a $COVER ]; then
+	if [ ! -f "$COVER" ] && [ "$COVER" != 0 ]; then
 		for IMAGE in $(find . -maxdepth 2 -iname *.png); do
-	    	image=$( echo ${IMAGE,,} | sed 's/.*\/\(.*\)\.png/\1/' )
+	    	image=$( echo $IMAGE | sed -e 's/\(.*\)/\L\1/' -e 's/.*\/\(.*\)\.png/\1/' )
 		    if [ "$image" == "cover" ] || [ "$image" == ".cover" ]; then
 				COVER=$IMAGE; break
 			elif [ "$image" == "folder" ] || [ "$image" == ".folder" ]; then
@@ -68,35 +69,38 @@ main(){
 		fi
 		# count the number of lines in the TRACK section of the cue file
 		fields=0
-		line=$( grep -n "TRACK $TRACKNUMBER" "$CUE" | awk '{print $1}' | sed 's/://' ) 
-		while ! grep -A $fields "TRACK $TRACKNUMBER" "$CUE" |
-			grep -v "TRACK $TRACKNUMBER" |
+		line=$( grep -n "TRACK\s\s*$TRACKNUMBER" "$CUE" | awk '{print $1}' | sed 's/://' ) 
+		while ! grep -A $fields "TRACK\s\s*$TRACKNUMBER" "$CUE" |
+			grep -v "TRACK\s\s*$TRACKNUMBER" |
 			grep TRACK > /dev/null &&
 			[ $( expr $( cat "$CUE" | wc -l ) - $line ) -gt $fields ]
 		do
 			fields=$( expr $fields + 1 )
 		done
 		# Gather per-track metadata
-		START=$( grep -A $fields "TRACK $TRACKNUMBER" "$CUE" |
-			grep "INDEX 01" |
-			sed -e 's/.*INDEX\s01\s\(..:..:..\).$/\1/' -e 's/:/./2' )
+		START=$( grep -A $fields "TRACK\s\s*$TRACKNUMBER" "$CUE" |
+			grep '\s*INDEX\s\s*01' |
+			sed -e 's/\s*INDEX\s\s*01\s\s*\([0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}\).*$/\1/' -e 's/:/./2' )
 		if [ -n "$pregap" ] || [ $TRACKNUMBER -eq 01 ] &&
-			grep -A $fields "TRACK $TRACKNUMBER" "$CUE" |
-			grep "INDEX 00" > /dev/null
+			grep -A $fields "TRACK\s\s*$TRACKNUMBER" "$CUE" |
+			grep 'INDEX\s\s*00\s\s*[0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}' > /dev/null
 		then
-			START=$( grep -A $fields "TRACK $TRACKNUMBER" "$CUE" |
-				grep "INDEX 00" |
-				sed -e 's/.*INDEX\s00\s\(..:..:..\).$/\1/' -e 's/:/./2' )
+			START=$( grep -A $fields "TRACK\s\s*$TRACKNUMBER" "$CUE" |
+				grep 'INDEX\s\s*00\s\s*[0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}' |
+				sed -e 's/\s*INDEX\s\s*00\s\s*\([0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}\).*$/\1/' -e 's/:/./2' )
 		fi
-		TITLE=$( grep -A $fields "TRACK $TRACKNUMBER" "$CUE" |
+		if [ -z "$START" ]; then
+			>&2 echo "$name: Missing or malformed initial index for track $TRACKNUMBER!"
+		fi
+		TITLE=$( grep -A $fields "TRACK\s\s*$TRACKNUMBER" "$CUE" |
 			grep TITLE |
-			sed 's/^.*TITLE\s\"\(.*\)\".$/\1/' )
-		PERFORMER=$( grep -A $fields "TRACK $TRACKNUMBER" "$CUE" |
+			sed 's/^.*TITLE\s\s*\"\(.*\)\".$/\1/' )
+		PERFORMER=$( grep -A $fields "TRACK\s\s*$TRACKNUMBER" "$CUE" |
 			grep PERFORMER |
-			sed 's/^.*PERFORMER\s\"\(.*\)\".$/\1/' )
-		SONGWRITER=$( grep -A $fields "TRACK $TRACKNUMBER" "$CUE" |
+			sed 's/^.*PERFORMER\s\s*\"\(.*\)\".$/\1/' )
+		SONGWRITER=$( grep -A $fields "TRACK\s\s*$TRACKNUMBER" "$CUE" |
 			grep SONGWRITER |
-			sed 's/^.*SONGWRITER\s\"\(.*\)\".$/\1/' )
+			sed 's/^.*SONGWRITER\s\s*\"\(.*\)\".$/\1/' )
 		# Set the tags and file names
 		if [ -n "$TITLE" ]; then
 			TAGS="$TAGS --tag=TITLE=\"$TITLE\""
@@ -109,14 +113,18 @@ main(){
 		elif [ -n "$PERFORMER" ]; then
 			TAGS="$TAGS --tag=ARTIST=\"$PERFORMER\""
 		fi
-		for FIELD in "ALBUM" "GENRE" "DATE"; do
-			if [ -n "${!FIELD}" ]; then
-				TAGS="$TAGS --tag=$FIELD=\"${!FIELD}\""
-			fi
-		done
+		if [ -n "$ALBUM" ]; then
+			TAGS="$TAGS --tag=ALBUM=\"$ALBUM\""
+		fi
+		if [ -n "$GENRE" ]; then
+			TAGS="$TAGS --tag=GENRE=\"$GENRE\""
+		fi
+		if [ -n "$DATE" ]; then
+			TAGS="$TAGS --tag=DATE=\"$DATE\""
+		fi
 		TAGS="$TAGS --tag=TRACKNUMBER=$TRACKNUMBER"
 		TAGS="$TAGS --tag=TRACKTOTAL=$TRACKTOTAL"
-		if [ -a "$COVER" ]; then
+		if [ -f "$COVER" ]; then
 			TAGS="$TAGS --picture=\"$COVER\""
 		fi
 		if [ -n "$TITLE" ]; then
@@ -124,7 +132,7 @@ main(){
 		else
 			NAME="TRACK $TRACKNUMBER.flac"
 		fi
-		if [ -a "$NAME" ] && [ -z "$force" ]; then
+		if [ -f "$NAME" ] && [ -z "$force" ]; then
 			echo "$name: Exsisting file will not be recreated: \"$NAME\""
 		fi
 		NAME=\"$NAME\"
@@ -135,34 +143,33 @@ main(){
 				TRACKNUMBER=0$TRACKNUMBER;
 			fi
 			fields=0
-			line=$( grep -n "TRACK $TRACKNUMBER" "$CUE" | awk '{print $1}' | sed 's/://' ) 
-			while ! grep -A $fields "TRACK $TRACKNUMBER" "$CUE" |
-				grep -v "TRACK $TRACKNUMBER" |
+			line=$( grep -n "TRACK\s\s*$TRACKNUMBER" "$CUE" | awk '{print $1}' | sed 's/://' ) 
+			while ! grep -A $fields "TRACK\s\s*$TRACKNUMBER" "$CUE" |
+				grep -v "TRACK\s\s*$TRACKNUMBER" |
 				grep TRACK > /dev/null &&
 				[ $( expr $( cat "$CUE" | wc -l ) - $line ) -gt $fields ]
 			do
 				fields=$( expr $fields + 1 )
 			done
-			END=$( grep -A $fields "TRACK $TRACKNUMBER" "$CUE" |
-				grep "INDEX 01" |
-				sed -e 's/.*INDEX\s01\s\(..:..:..\).$/\1/' -e 's/:/./2' )
+			END=$( grep -A $fields "TRACK\s\s*$TRACKNUMBER" "$CUE" |
+				grep "INDEX\s\s*01" |
+				sed -e 's/\s*INDEX\s\s*01\s\s*\([0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}\).*$/\1/' -e 's/:/./2' )
 			if [ -n "$pregap" ] &&
-				grep -A $fields "TRACK $TRACKNUMBER" "$CUE" |
+				grep -A $fields "TRACK\s\s*$TRACKNUMBER" "$CUE" |
 				grep "INDEX 00" > /dev/null
 			then
-				END=$( grep -A $fields "TRACK $TRACKNUMBER" "$CUE" |
+				END=$( grep -A $fields "TRACK\s\s*$TRACKNUMBER" "$CUE" |
 					grep "INDEX 00" |
-					sed -e 's/.*INDEX\s00\s\(..:..:..\).$/\1/' -e 's/:/./2' )
+					sed -e 's/\s*INDEX\s\s*00\s\s*\([0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}\).*$/\1/' -e 's/:/./2' )
 			fi
 			# Create the files
 			flac -c -d --totally-silent --skip=$START --until=$END "$FILE" |
 			eval flac --totally-silent $OPTS $TAGS -o $NAME - &
 		else
 			flac -c -d --totally-silent --skip=$START "$FILE" |
-			eval flac --totally-silent $OPTS $TAGS -o $NAME - 
+			eval flac --totally-silent $OPTS $TAGS -o $NAME - &
 		fi
 	done
-	S=$?
 }
 usage(){ # the --help text
 echo "Usage: $name [options] <file.cue>
@@ -203,7 +210,7 @@ guess(){ # Try to find an audio file if the one in the cue doesn't exist
 	fi
 	IFS=$oldIFS
 }
-name=$( echo $0 | sed 's/.*\///' ); S=1
+name=$( echo $0 | sed 's/.*\///' )
 # Check for options that have been enabled
 if [ $# -eq 0 ]; then
 	usage & exit 1
@@ -212,33 +219,34 @@ while [ $# -gt 0 ]; do
 	case $1 in
 		-h | --help )	usage & exit;;
 		-g | --pregap )	pregap=0; shift;;
-		-f | --force )	OPTS="$OPTS -f" & force=0; shift;;
+		-f | --force )	OPTS="$OPTS -f" ; force=0; shift;;
 		-0 | -1 | -2 | -3 | -4 | -5 | -6 | -7 | -8 ) OPTS="$OPTS $1"; shift;;
+		--picture= )	COVER=0; shift;;
 		--picture=* )	COVER=$( echo $1 | sed 's/--picture=//' ); shift;;
 		*)				CUE="$1"; shift;;
 	esac
 done
 # Make sure that the remaining parameter is a cue file and that we can find the
 # corrosponding audio file before passing it to the main function
-cue=${CUE,,}
+cue=$( echo $CUE | sed 's/\(.*\)/\L\1/' )
 if [ -z "$CUE" ]; then
 	echo ONE
 	>&2 echo "$name: No cue file specified."
 	exit 1
-elif [ "$cue" != "${cue%.cue}" ]; then
+elif [ "$cue" != "$( echo $cue | sed 's/\.cue$//' )" ]; then
 	FILE=$( grep FILE "$CUE" | grep -o \".*\" | sed 's/^"\(.*\)"$/\1/' )
 	if [ $( echo "$FILE" | wc -l ) -gt 1 ]; then
 		echo -e "$name: Multiple audio files are listed in the cue.\n"\
 		" The album has probably already been split into tracks."
   		exit
-	elif ! [ -a "$FILE" ]; then
+	elif [ ! -f "$FILE" ]; then
 		echo "$name: Could not find the audio file in the cue: $FILE"
 		FILE=$(guess)
-		if [ -a "$FILE" ]; then
+		if [ -f "$FILE" ]; then
 			echo "$name: Using $FILE instead."
 		fi
 	fi
-	if [ -a "$FILE" ]; then
+	if [ -f "$FILE" ]; then
 		main
 	else
 		exit 1
@@ -247,4 +255,4 @@ else
 	>&2 echo "$name: \"$CUE\" is neither a cue file nor a valid option."
 	exit 1
 fi
-eval exit $S
+
