Simpler and more portable

diff --git a/flactrack b/flactrack
--- a/flactrack
+++ b/flactrack
@@ -38,7 +38,7 @@ main(){
 	oldIFS=$IFS && IFS=$(echo -en "\n\b")
 	if [ ! -f "$COVER" ] && [ "$COVER" != 0 ]; then
 		for IMAGE in $( find . -maxdepth 2 \( -iname \*.jpg -o -iname \*.jpeg \) ); do
-		    image=$( echo $IMAGE | sed -e 's/\(.*\)/\L\1/' -e 's/.*\/\(.*\)\.jpe\?g/\1/' )
+		    image=$( echo $IMAGE | tr A-Z a-z | sed 's/.*\/\(.*\)\.jpe\?g/\1/' )
 		    if [ "$image" == "cover" ] || [ "$image" == ".cover" ]; then
 				COVER=$IMAGE; break
 			elif [ "$image" == "folder" ] || [ "$image" == ".folder" ]; then
@@ -50,7 +50,7 @@ main(){
 	fi
 	if [ ! -f "$COVER" ] && [ "$COVER" != 0 ]; then
 		for IMAGE in $(find . -maxdepth 2 -iname *.png); do
-	    	image=$( echo $IMAGE | sed -e 's/\(.*\)/\L\1/' -e 's/.*\/\(.*\)\.png/\1/' )
+	    	image=$( echo $IMAGE | tr A-Z a-z | sed 's/.*\/\(.*\)\.png/\1/' )
 		    if [ "$image" == "cover" ] || [ "$image" == ".cover" ]; then
 				COVER=$IMAGE; break
 			elif [ "$image" == "folder" ] || [ "$image" == ".folder" ]; then
@@ -88,8 +88,8 @@ main(){
 				grep 'INDEX\s\s*00\s\s*[0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}' |
 				sed -e 's/\s*INDEX\s\s*00\s\s*\([0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}\).*$/\1/' -e 's/:/./2' )
 		fi
-		if [ -z "$START" ]; then
-			>&2 echo "$name: Missing or malformed initial index for track $TRACKNUMBER!"
+		if [ "$START" != "$( echo $START | grep '[0-9]\{2\}:[0-9]\{2\}\.[0-9]\{2\}' )" ]; then
+			>&2 echo "$name: Missing or malformed initial index for track $TRACKNUMBER"
 		fi
 		TITLE=$( grep -A $fields "TRACK\s\s*$TRACKNUMBER" "$CUE" |
 			grep TITLE |
@@ -235,12 +235,10 @@ while [ $# -gt 0 ]; do
 done
 # Make sure that the remaining parameter is a cue file and that we can find the
 # corrosponding audio file before passing it to the main function
-cue=$( echo $CUE | sed 's/\(.*\)/\L\1/' )
 if [ -z "$CUE" ]; then
-	echo ONE
 	>&2 echo "$name: No cue file specified."
 	exit 1
-elif [ "$cue" != "$( echo $cue | sed 's/\.cue$//' )" ]; then
+elif echo $CUE | grep -i '\.cue$'; then
 	FILE=$( grep FILE "$CUE" | grep -o \".*\" | sed 's/^"\(.*\)"$/\1/' )
 	if [ $( echo "$FILE" | wc -l ) -gt 1 ]; then
 		echo -e "$name: Multiple audio files are listed in the cue.\n"\
